mkdir data
mkdir results
cd results
mkdir 01-make-manifest
mkdir 02-make-artifact
mkdir 03-infer-asv
mkdir 04-merge-table
mkdir 05-make-phylogeny
mkdir 06-make-rarefaction-curve
mkdir 07-export-rarefaction-curve
mkdir 08-calculate-plateau
mkdir 09-rarefy
mkdir 10-assign-taxa
cd ..